BaSD-MS-W8-003:Postulants resource
nicolasviola/BaSD-MindSet pull request #4
Opened 2021-11-06 20:04 UTC by MicaQuarleri

**Entity created:** Postulants
**Endpoints created:**
> - Create postulant
> - Edit postulant
> - Delete postulant
> - List Postulants

2021-11-06 21:48 UTC, AgustinCarthery commented on controllers/postulants.js
> +	}
posterior a realizar el push habria que reescribir el json: 
fs.writeFile('./data/postulants.json', JSON.stringify(Postulants), {}, (error) => { ... }

2021-11-06 21:48 UTC, AgustinCarthery commented on .gitignore
> -package-lock.json
mica no elimines lo comentado en el node_modules ni el package-lock.json son archivos que no tienen que subirse al repo, esto lo que genera es que se suba la carpeta entera de node_modules lo cual va a hacer muy pesado el proyecto

2021-11-07 01:00 UTC, nicolasviola requested changes

2021-11-07 19:48 UTC, AgustinCarthery commented
@MicaQuarleri closed due to node_modules fix on .gitignore file

2021-11-07 19:48 UTC, closed without merging